import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Table from 'react-bootstrap/Table';
  
interface AppReviewItem {
  USER: string,
  TITLE: string,
  REVIEW: string,
  STAR: string,
  LIKE: string,
  DATE: Date,
}

export default function Home2() {
  const [appReviews, setAppReviews] = useState<AppReviewItem[]>([])
  const getAppreviews = async () => {
    const {data} = await axios.get<AppReviewItem[]>(`${process.env.API_URL}/review/file`);
    setAppReviews(data);
  }

  // function add_row(data: any) {
  //   let result = [];
  //   for(let row of data) {
  //     console.log(row);
  //       for(let cell of row){
  //         result.push('<tr>');
  //         result.push(`<td>number</td>`);
  //         result.push(`<td>${cell.USER}</td>`);
  //         result.push(`<td>${cell.TITLE}</td>`);
  //         result.push(`<td>${cell.REVIEW}</td>`);
  //         result.push(`<td>${cell.STAR}</td>`);
  //         result.push(`<td>${cell.LIKE}</td>`);
  //         result.push(`<td>${cell.DATE}</td>`);
  //         result.push('</tr>');
  //       }
  //   }
  //   return result.join('\n');
  // }

  useEffect(() =>{
    getAppreviews()
  },[])
  return (
    
    <div className={styles.container}>
      <h1> app_name </h1>
      <Head>
        <title> app_name </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Table striped bordered hover>
      <thead>
        <tr>
          <th>#</th>
          <th>User Name</th>
          <th>Title</th>
          <th>review</th>
          <th>Star</th>
          <th>Like</th>
          <th>Date</th>
        </tr>
      </thead>                        {/*  foreach 문으로 바꾸자 나중에 */}
      {   
        appReviews.map((cell: AppReviewItem)=> ( // <= 괄호 안에 html 코드 넣으면 스트링으로 넘겨주지 않고 HTML로 전달하겠다는 의미
          <tr key={appReviews.indexOf(cell)}>
          <td>{appReviews.indexOf(cell) + 1}</td>
          <td>{cell.USER}</td>
          <td>{cell.TITLE}</td>
          <td>{cell.REVIEW}</td>
          <td>{cell.STAR}</td>
          <td>{cell.LIKE}</td>
          <td>{cell.DATE.toString()}</td>
        </tr>
        ))
      }
      </Table>
      </main>
    </div>
  )
}
