import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Table from 'react-bootstrap/Table';
import Link from 'next/link'
// https://react-bootstrap.github.io/components/table/

interface AppInfo { 
  id: number,
  app_id: string,
  app_name: string,
  OS: string,
}

export default function Home() {
  const [apps, setAppList] = useState<AppInfo[]>([])
  const getApps = async () => {
    const {data} = await axios.get<AppInfo[]>(`${process.env.API_URL}/Moapp/all`);
    setAppList(data);
     //console.log(data);
  }
  useEffect(() =>{
    getApps()
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Table striped bordered hover>
      <thead>
        <tr>
          <th>#</th>
          <th>App Name</th>
          <th>App ID</th>
          <th>OS</th>
        </tr>
      </thead>                        {/*  foreach 문으로 바꾸자 나중에 */}
      <tbody>
        
        { // 이게 반복문. app이란 아이템을 계속 넣어줌. apps의 배열이 끝날 때까지 app의 아이템들을 넣어주어 화살표 함수 내의 처리를 반복함.
          apps.map((app: AppInfo)=> (
            <tr key={app.app_id}>
              <td>{apps.indexOf(app) + 1}</td>
              <td><Link href={`/appDetail?app_id=${app.app_id}`}>{app.app_name}</Link></td>
              <td>{app.app_id}</td>
              <td>{app.OS}</td>
            </tr>
          ))
        }
          {/* <tr>
            <td>1</td>
            <td><Link href='/appDetail'>{apps.filter((app: any) => app.id == 1).map((app : any) => app.app_name)}</Link></td>
            <td>{apps.filter((app: any) => app.id == 1).map((app : any) => app.app_id)}</td>
            <td>{apps.filter((app: any) => app.id == 1).map((app : any) => app.OS)}</td>
          </tr>
        
        <tr>
          <td>2</td>
          <td>{apps.filter((app: any) => app.id == 2).map((app : any) => app.app_name)}</td>
          <td>{apps.filter((app: any) => app.id == 2).map((app : any) => app.app_id)}</td>
          <td>{apps.filter((app: any) => app.id == 2).map((app : any) => app.OS)}</td>
        </tr> */}
        {/* <tr>
          <td>3</td>
          <td colSpan={2}>Larry the Bird</td>
          <td>@twitter</td>
        </tr> */}
      </tbody>
    </Table>
      </main>
    </div>
  )
}
